### ISSUE TITLE
Expose Battery Level as Entity

### ISSUE THREAD

**Issue by bzumik1** [joerg65/tedee_lock#11]
Hi, would it be possible to expose battery level / battery charging as entity not as attribute? It would make it easier to add this information on dashboard.

**Comment by joerg65** [comment]
Does not HACS: battery-entity-row give you what you want?
```
type: entities
entities:
  - type: custom:battery-entity-row
    entity: lock.lock_326b
    attribute: battery_level
    name: Lock battery
    unit: percent
    icon: mdi:battery
    secondary_info: last-changed
    warning: 50
    critical: 25
    charging: false
```
![Bildschirmfoto vom 2023-06-28 12-57-24](https://github.com/joerg65/tedee_lock/assets/18566178/c7fced11-9a2d-41ff-8dd3-3b6741e62bc8)

**Comment by bzumik1** [comment]
Hi Joerg65,

the proposed will work but to me it looks more like workaround isn't it? I might be wrong though.

**Comment by joerg65** [comment]
I don't see that things one can do with HA are a workaround. You even don't need to import a custom integration. Whit integrations that are in HA included, can be created a sensor from any attribute. A separate battery entity from a device that is a lock seems for me overwhelmed, or even rare. I definitely won't add this to the integration, as I already decided to do no more work on it.
Here is another method with HA onboard integration:
```
template:
  sensor:
    - name: "Lock Battery Level"
      state: "{{ state_attr('lock.lock_326b', 'battery_level') }}"
      unit_of_measurement: "%"
      device_class: battery
```
